---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/login":
    post:
      summary: return token and user info
      tags:
      - login
      parameters: []
      responses:
        '200':
          description: return tokens
        '401':
          description: bad password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/warehouses":
    get:
      summary: return correct list
      tags:
      - Список складов
      responses:
        '200':
          description: correct response
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
