---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/login":
    post:
      summary: return token and user info
      tags:
      - login
      parameters: []
      responses:
        '200':
          description: return tokens
        '401':
          description: bad password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/cities":
    get:
      summary: list cities
      tags:
      - cities
      responses:
        '200':
          description: correct response
  "/api/orders":
    get:
      summary: list orders
      tags:
      - orders
      security:
      - Bearer: {}
      responses:
        '200':
          description: empty list
        '401':
          description: not authorization
    post:
      summary: create order
      tags:
      - orders
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: create hight rule user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: number
                receiver_id:
                  type: number
                start_warehouse_id:
                  type: number
                end_warehouse_id:
                  type: number
              required:
              - start_warehouse_id,
              - end_warehouse_id
  "/api/warehouses":
    get:
      summary: return correct list
      tags:
      - Список складов
      responses:
        '200':
          description: correct response
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      type: apiKey
      in: header
      name: Authorization
